name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Convertir le pseudo GitHub en minuscules
        run: echo "GHCR_USER=${GITHUB_ACTOR,,}" >> $GITHUB_ENV

      - name: Connexion à GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construire et tagger l'image Docker
        run: |
          IMAGE_NAME=ghcr.io/${{ env.GHCR_USER }}/pdf-api
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Pousser l'image vers GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ env.GHCR_USER }}/pdf-api
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
